FROM yazhinban/kinesis-kafka-connector:latest

RUN mkdir -p jmx/ && wget -o jmx/jmx_prometheus_javaagent.jar https://repo.maven.apache.org/maven2/io/prometheus/jmx/jmx_prometheus_javaagent/0.20.0/jmx_prometheus_javaagent-0.20.0.jar
